module.exports.ROUTE_CONSTANTS={
    DEFAULT:"/",
    GET_PRODUCTS:"/products",
    GET_LOGIN:"/login",
    GET_REGISTER:"/REGISTER",
    POST_REGISTER:'/register',
    POST_LOGIN:'/login',
    GET_COUNTRIES:'/countryList'
}